### ISSUE TITLE
Error: Expected a value of type 'Object', but got one of type 'Null'

### ISSUE THREAD

**Issue by devj3ns** [simpleclub/url_strategy#14]
Hey, when I start my Flutter web app I get this error when I'm using this package:

```
Error: Expected a value of type 'Object', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:60029/dart_sdk.js:5032:11)
    at Object.castError (http://localhost:60029/dart_sdk.js:5005:15)
    at Object.cast [as as] (http://localhost:60029/dart_sdk.js:5314:17)
    at Function.as (http://localhost:60029/dart_sdk.js:6508:31)
    at Object._argumentErrors (http://localhost:60029/dart_sdk.js:5150:19)
    at Object._checkAndCall (http://localhost:60029/dart_sdk.js:5233:29)
    at Object.dcall (http://localhost:60029/dart_sdk.js:5242:17)
    at Object.ret [as replaceState] (http://localhost:60029/dart_sdk.js:57497:21)
    at _engine.CustomUrlStrategy.fromJs.replaceState (http://localhost:60029/dart_sdk.js:140910:28)
    at _engine.MultiEntriesBrowserHistory.new.tearDown (http://localhost:60029/dart_sdk.js:140622:42)
    at tearDown.next (<anonymous>)
    at runBody (http://localhost:60029/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:60029/dart_sdk.js:37260:7)
    at _engine.MultiEntriesBrowserHistory.new.tearDown (http://localhost:60029/dart_sdk.js:140609:20)
    at _engine.EngineSingletonFlutterWindow.new._useSingleEntryBrowserHistory (http://localhost:60029/dart_sdk.js:170475:76)
    at _useSingleEntryBrowserHistory.next (<anonymous>)
    at runBody (http://localhost:60029/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:60029/dart_sdk.js:37260:7)
    at _engine.EngineSingletonFlutterWindow.new.[_useSingleEntryBrowserHistory] (http://localhost:60029/dart_sdk.js:170469:20)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:60029/dart_sdk.js:170521:56)
    at handleNavigationMessage.next (<anonymous>)
    at runBody (http://localhost:60029/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:60029/dart_sdk.js:37260:7)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:60029/dart_sdk.js:170514:20)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:60029/dart_sdk.js:155384:68)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:60029/dart_sdk.js:155214:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:60029/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
    at _DefaultBinaryMessenger.send (http://localhost:60029/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:60029/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
    at _invokeMethod.next (<anonymous>)
```

The functionality, however, works fine. I am using Flutter 2.0.1 stable and version 0.2.0 of this package.

**Comment by creativecreatorormaybenot** [comment]
Hi @devj3ns 🙂  Thanks a lot for opening the issue ❤️ 

I think this is an issue with Flutter that I cannot do anything about (in this package). So I would suggest opening this issue at https://github.com/flutter/flutter/issues instead :)

**Comment by devj3ns** [comment]
See https://github.com/flutter/flutter/issues/78017 for more details.

**Comment by danieldoddjr** [comment]
This is a package issue that shows up when null safety is running. I remove the package and zero errors!

**Comment by creativecreatorormaybenot** [comment]
What do you mean by "I remove the package" @danieldoddjr?

Are you **also** removing the function all? :) In this case, what I said before still holds true. The function that is called in this package is part of the Flutter SDK, which is why it belongs to flutter/flutter#78017.

**Comment by creativecreatorormaybenot** [comment]
I understand your frustration @danieldoddjr ❤️ The issue here is not with the package, however. The package directly calls a function from the Flutter framework (see https://github.com/flutter/flutter/issues/78017#issuecomment-807466285).

The type error happens within the framework code, not within the package code.

**Comment by isanecat** [comment]
I have exactly the same issue for web with Flutter 2.10.1 stable. But Android works properly.

**Comment by yurrpt** [comment]
While my app works fine on Android and IOS, I get the same error on the web.


**`Error: Expected a value of type 'Object', but got one of type 'Null'`**

i packages use 
#db
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_crashlytics: ^3.0.5
  firebase_database: ^10.0.1
  firebase_messaging: ^14.1.0
  #web
  firebase_core_web: ^2.0.1
  firebase_analytics_web: ^0.5.1+4
  firebase_auth_web: ^5.1.2
  firebase_messaging_web: ^3.2.6

Here is the error output



```
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 470:10  cast
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 73:24                 as
packages/firebase_core_web/src/firebase_core_web.dart 64:20                                                                    get [_ignoredServiceScripts]
packages/firebase_core_web/src/firebase_core_web.dart 115:28                                                                   _initializeCore
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 107:31                                                                   [_initializeCore]
packages/firebase_core_web/src/firebase_core_web.dart 149:11                                                                   initializeApp
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/firebase_core_web/src/firebase_core_web.dart 145:44                                                                   initializeApp
packages/firebase_core/src/firebase.dart 43:47                                                                                 initializeApp
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/firebase_core/src/firebase.dart 39:43                                                                                 initializeApp
packages/swivenetworkproject/main.dart 28:18                                                                                   main
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 85:54                runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 124:5                _async
packages/swivenetworkproject/main.dart 26:18                                                                                   main$
web_entrypoint.dart 24:31                                                                                                      <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 352:37  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 357:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/lib/ui/initialization.dart 77:15                                                  <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 46:50                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1660:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                         [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7                                         callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 167:15               <fn>
```
